In [3]:
!pip install tensorflow

import tensorflow as tf
print(tf.__version__)

a = tf.constant(5)
print(a)

v=tf.constant([1,2,3,4])
print(v)

m=tf.constant([[1,2,3],[4,5,6]])
print(m)

t3=tf.constant([[[1,2,3],[4,5,6],[7,8,9]]])
print(t3)

"""Tensor Addition

"""

a = tf.constant([10,20,30])
b = tf.constant([50,60,70])

print(a+b)



"""Addition of scalars"""

a = tf.constant(10)
b = tf.constant(20)

print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**b)



"""Vector Addititon"""

a = tf.constant([1,2])
b = tf.constant([3,2])

print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**b)



"""addititon of 2-D Vectors"""

a = tf.constant([[1,2],[1,2]])
b = tf.constant([[2,1],[2,1]])

print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**b)



"""Data types, shape , number of dimensions

"""

t= tf.constant([[1, 2, 3],[4, 5, 6]])
print(t.dtype)
print(t.shape)
print(t.ndim)

import numpy as np

numpy_array = np.array([10, 20, 30, 40])

tensor = tf.convert_to_tensor(numpy_array)

print("NumPy Array:",numpy_array)


print("\nTensorFlow Tensor:",tensor)



2.19.0
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[[1 2 3]
  [4 5 6]
  [7 8 9]]], shape=(1, 3, 3), dtype=int32)
tf.Tensor([ 60  80 100], shape=(3,), dtype=int32)
tf.Tensor(30, shape=(), dtype=int32)
tf.Tensor(-10, shape=(), dtype=int32)
tf.Tensor(200, shape=(), dtype=int32)
tf.Tensor(0.5, shape=(), dtype=float64)
tf.Tensor(1661992960, shape=(), dtype=int32)
tf.Tensor([4 4], shape=(2,), dtype=int32)
tf.Tensor([-2  0], shape=(2,), dtype=int32)
tf.Tensor([3 4], shape=(2,), dtype=int32)
tf.Tensor([0.33333333 1.        ], shape=(2,), dtype=float64)
tf.Tensor([1 4], shape=(2,), dtype=int32)
tf.Tensor(
[[3 3]
 [3 3]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[-1  1]
 [-1  1]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[2 2]
 [2 2]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[0.5 2. ]
 [0.5 2. ]], shape=(2, 2), dtype=float64)
tf.Tensor(
[[1 2]
 [1 2]], shape=(2, 2), dtype=int32)
<dtype: 'int32'